name: CI for website-source

on: [watch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 配置Git
      run: | 
        git config --global user.name 'wztlink1013' 
        git config --global user.email '2550374815@qq.com'

    - name: 在云端进行复制文件夹操作
      env:
        Github_Token: ${{ secrets.TOKEN_GITHUBAPI }}
      run: | 
        git clone https://github.com/wztlink1013/test test
        cd test
        cp -r ./js/ ./backup/
        git status
        git add .
        git commit -m "CI for website-source"
        git push --force --quiet "https://${Github_Token}@github.com/wztlink1013/test"  master:master
